//==================================================
// This file contains the Excluded objects
// Generated By User: udij
// Format Version: 2
// Date: Fri Dec 20 10:22:53 2019
// ExclMode: default
//==================================================
CHECKSUM: "855201581"
INSTANCE:core_ibex_tb_top.dut.u_ibex_tracer
CHECKSUM: "3925354628 2975514524"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.load_store_unit_i
Block 14 "741245962" "data_be = 'x;"
Block 89 "3010406125" "data_rdata_ext = 'x;"
Block 84 "315336069" "rdata_b_ext = 'x;"
Block 56 "853832096" "rdata_w_ext = 'x;"
Block 29 "435594639" "data_be = 'x;"
Block 28 "2405901750" "data_be = 'x;"
Block 21 "580609842" "data_be = 'x;"
Block 70 "1173085715" "rdata_h_ext = 'x;"
CHECKSUM: "1900529272 3306234756"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.id_stage_i.decoder_i
Block 66 "3526321295" "alu_operator_o = alu_op_e'({5 {1'bx}});"
CHECKSUM: "4202009924 1468962457"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.if_stage_i
Block 6 "1757598809" "exc_pc = 'x;"
Block 13 "3448796908" "fetch_addr_n = 'x;"
CHECKSUM: "551604268 385887848"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.ex_block_i.gen_multdiv_fast.multdiv_i
Block 44 "1159255408" "mult_state_n = mult_fsm_e'(1'bx);"
CHECKSUM: "911797751 1474435198"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.if_stage_i.compressed_decoder_i
Block 30 "1282525428" "illegal_instr_o = 1'bx;"
Block 54 "2356913921" "illegal_instr_o = 1'bx;"
Block 33 "2455191530" "illegal_instr_o = 1'bx;"
Block 31 "448892625" "illegal_instr_o = 1'bx;"
CHECKSUM: "3406622181 1584873194"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.cs_registers_i
Block 74 "3877431428" ";"
CHECKSUM: "4202009924 3139560230"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.if_stage_i
Branch 1 "737823291" "pc_mux_i" (5) "pc_mux_i default"
Branch 0 "2708846381" "exc_pc_mux_i" (4) "exc_pc_mux_i default"
CHECKSUM: "3925354628 1568720443"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.load_store_unit_i
Branch 5 "450224103" "rdata_offset_q" (4) "rdata_offset_q default"
Branch 7 "1005870506" "rdata_offset_q" (8) "rdata_offset_q default,-,-,-,-"
Branch 6 "1005870506" "rdata_offset_q" (8) "rdata_offset_q default,-,-,-,-"
Branch 8 "2414809973" "data_type_q" (3) "data_type_q default"
Branch 0 "813603843" "data_type_ex_i" (14) "data_type_ex_i 2'b01 ,-,-,-,1,default,-"
Branch 0 "813603843" "data_type_ex_i" (20) "data_type_ex_i 2'b10 2'b11 ,-,-,-,-,-,default"
Branch 0 "813603843" "data_type_ex_i" (21) "data_type_ex_i default,-,-,-,-,-,-"
Branch 0 "813603843" "data_type_ex_i" (9) "data_type_ex_i 2'b00 ,0,-,default,-,-,-"
CHECKSUM: "551604268 2014072110"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.ex_block_i.gen_multdiv_fast.multdiv_i
Branch 6 "139634448" "mult_state_q" (6) "mult_state_q default,-,-"
CHECKSUM: "211515890 1106146130"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.ex_block_i.alu_i
Branch 8 "1307726770" "operator_i" (6) "operator_i default"
CHECKSUM: "911797751 1505998573"
INSTANCE: core_ibex_tb_top.dut.u_ibex_core.if_stage_i.compressed_decoder_i
Branch 0 "4072320035" "instr_i[1:0]" (21) "instr_i[1:0] 2'b01 ,-,-,3'b100 ,-,-,default,-,-,-,-,-,-,-,-,-,-"
Branch 0 "4072320035" "instr_i[1:0]" (23) "instr_i[1:0] 2'b01 ,-,-,default,-,-,-,-,-,-,-,-,-,-,-,-,-"
Branch 0 "4072320035" "instr_i[1:0]" (36) "instr_i[1:0] 2'b10 ,-,-,-,-,-,-,-,-,default,-,-,-,-,-,-,-"
Branch 0 "4072320035" "instr_i[1:0]" (20) "instr_i[1:0] 2'b01 ,-,-,3'b100 ,-,-,2'b11 ,-,default,-,-,-,-,-,-,-,-"
