+define+RVFI=1
+define+RV32M=ibex_pkg::RV32MSingleCycle
+define+RV32B=ibex_pkg::RV32BNone
+define+RegFile=ibex_pkg::RegFileFF
-pvalue+tb_lca_system.RV32E=0
-pvalue+tb_lca_system.ICache=1
-pvalue+tb_lca_system.ICacheScramble=1
-pvalue+tb_lca_system.ICacheECC=0
-pvalue+tb_lca_system.BranchTargetALU=0
-pvalue+tb_lca_system.WritebackStage=0
-pvalue+tb_lca_system.SecureIbex=0
-pvalue+tb_lca_system.BranchPredictor=0
-pvalue+tb_lca_system.DbgTriggerEn=0
-pvalue+tb_lca_system.PMPEnable=0
-pvalue+tb_lca_system.PMPGranularity=0
-pvalue+tb_lca_system.PMPNumRegions=4
-pvalue+tb_lca_system.MHPMCounterNum=0
-pvalue+tb_lca_system.MHPMCounterWidth=40
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/tb/remote_bitbang
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/dv/prim_prince/crypto_dpi_prince
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/sv/dv_utils
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/dv/prim_secded
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/dv/prim_ram_scr/cpp
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp
+incdir+/home/samuel_matea/ws-isolde/ibex_sam/rtl
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/tb/remote_bitbang/remote_bitbang.c
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/tb/remote_bitbang/sim_jtag.c
/home/samuel_matea/ws-isolde/ibex_sam/vendor/core-v-xif/rtl/isolde_cv_x_if.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/core-v-xif/tb/xif_monitor_cpu_issue.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/dv/prim_secded/secded_enc.c
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_cv_x_if_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_register_file_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_decoder_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_and2.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_buf.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_gating.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_flop.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_22_16_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_28_22_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_39_32_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_64_57_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_72_64_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_64_57_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_64_57_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_72_64_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_and2.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_buf.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_clock_gating.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_clock_mux2.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_xilinx/rtl/prim_xilinx_flop.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/dv/prim_ram_scr/cpp/scramble_model.cc
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp/dpi_memutil.cc
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp/ecc32_mem_area.cc
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp/mem_area.cc
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp/sv_scoped.cc
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_icache.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_tracer_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_tracer.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_subst_perm.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_present.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_prince.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_count_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_ram_1p.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/dv/verilator/cpp/scrambled_ecc32_mem_area.cc
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_and2-impl_0/prim_and2.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_buf-impl_0/prim_buf.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_clock_gating-impl_0/prim_clock_gating.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_clock_mux2-impl_0/prim_clock_mux2.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_flop-impl_0/prim_flop.sv
/home/samuel_matea/ws-isolde/ibex_sam/dv/uvm/icache/dv/prim_badbit/prim_badbit_ram_1p.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_enc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_mux.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_check.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tmp/isolde/sim-vcs/generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi4_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi4_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi4_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi8_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi8_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi8_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi12_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi12_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi12_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi16_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi16_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi16_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi20_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi20_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi20_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi24_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi24_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi24_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi28_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi28_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi28_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi32_sender.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi32_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi32_dec.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_alu.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_branch_predict.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_compressed_decoder.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_controller.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_cs_registers.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_csr.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_decoder.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_ex_block.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_fetch_fifo.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_id_stage.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_if_stage.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_load_store_unit.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_multdiv_fast.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_multdiv_slow.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_prefetch_buffer.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_pmp.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_wb_stage.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_dummy_instr.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_core.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_fetch2exec_if.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_fetch_vleninstr.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_decoder.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_exec_block.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_adv.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_x_register_file_if.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_register_file_if.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/isolde_register_file_ff.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_register_file_ff.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_register_file_fpga.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_register_file_latch.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_lockstep.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_top.sv
/home/samuel_matea/ws-isolde/ibex_sam/rtl/ibex_top_tracing.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/rtl/tc_sram.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/rtl/tc_sram_impl.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/rtl/tc_clk.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/cluster_pwr_cells.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/generic_memory.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/generic_rom.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/pad_functional.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/pulp_buffer.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/pulp_pwr_cells.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/tc_pwr.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/pulp_clock_gating_async.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/cluster_clk_cells.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/tech_cells_generic-df3060162cb1741c/src/deprecated/pulp_clk_cells.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/binary_to_gray.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cb_filter_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cc_onehot.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_reset_ctrlr_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cf_math_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/clk_int_div.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/credit_counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/delta_counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/ecc_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/edge_propagator_tx.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/exp_backoff.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/fifo_v3.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/gray_to_binary.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/isochronous_4phase_handshake.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/isochronous_spill_register.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/lfsr.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/lfsr_16bit.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/lfsr_8bit.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/lossy_valid_to_stream.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/mv_filter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/onehot_to_bin.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/plru_tree.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/passthrough_stream_fifo.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/popcount.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/rr_arb_tree.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/rstgen_bypass.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/serial_deglitch.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/shift_reg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/shift_reg_gated.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/spill_register_flushable.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_demux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_filter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_fork.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_intf.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_join_dynamic.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_mux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_throttle.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/sub_per_hash.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/sync_wedge.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/unread.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/read.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/addr_decode_dync.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_2phase.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_4phase.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/clk_int_div_static.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/addr_decode.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/addr_decode_napot.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/multiaddr_decode.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cb_filter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_fifo_2phase.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/clk_mux_glitch_free.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/ecc_decode.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/ecc_encode.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/edge_detect.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/lzc.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/max_counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/rstgen.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/spill_register.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_delay.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_fifo.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_fork_dynamic.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_join.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_reset_ctrlr.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_fifo_gray.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/fall_through_register.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/id_queue.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_to_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_arbiter_flushable.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_fifo_optimal_wrap.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_register.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_xbar.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_fifo_gray_clearable.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/cdc_2phase_clearable.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/mem_to_banks_detailed.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_arbiter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/stream_omega_net.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/mem_to_banks.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/clock_divider_counter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/clk_div.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/find_first_one.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/generic_LFSR_8bit.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/generic_fifo.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/prioarbiter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/pulp_sync.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/pulp_sync_wedge.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/rrarbiter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/clock_divider.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/fifo_v2.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/deprecated/fifo_v1.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/edge_propagator_ack.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/edge_propagator.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/common_cells-5f8752ff87c3029a/src/edge_propagator_rx.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_intf.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_atop_filter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_burst_splitter_gran.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_burst_unwrap.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_bus_compare.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_cdc_dst.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_cdc_src.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_cut.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_delayer.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_demux_simple.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_dw_downsizer.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_dw_upsizer.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_fifo.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_fifo_delay_dyn.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_id_remap.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_id_prepend.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_isolate.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_join.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_demux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_dw_converter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_from_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_join.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_lfsr.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_mailbox.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_mux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_regs.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_to_apb.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_to_axi.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_modify_address.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_mux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_rw_join.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_rw_split.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_serializer.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_slave_compare.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_throttle.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_detailed_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_burst_splitter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_cdc.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_demux.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_err_slv.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_dw_converter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_from_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_id_serialize.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lfsr.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_multicut.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_axi_lite.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_zero_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_interleaved_xbar.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_iw_converter.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_lite_xbar.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_xbar_unmuxed.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_mem_banked.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_mem_interleaved.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_to_mem_split.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_xbar.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/.bender/git/checkouts/axi-5480d715b198aaaa/src/axi_xp.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_tiler.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_ctrl.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_scheduler.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_castin.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_castout.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_streamer.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_x_buffer.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_w_buffer.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_z_buffer.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_fma.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_noncomp.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_ce.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_row.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_engine.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_top.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/rtl/redmule_isolde.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/tb/tb_dummy_memory.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/tb/tb_tcdm_verilator.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/tb/redmule_tb.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/redmule/tb/tb_redmule_verilator.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/debug_rom/debug_rom.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_csrs.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dmi_cdc.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dmi_jtag_tap.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_sba.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_top.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dmi_jtag.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/src/dm_obi_top.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/riscv-dbg/tb/SimJTAG.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-dm/rtl/jtag_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-dm/rtl/rv_dm_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-dm/rtl/rv_dm.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/common/isolde_tcdm_pkg.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_tcdm_if.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_tcdm_to_axi.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_addr_shim.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_demux_tcdm.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_mux_tcdm.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_hci_interconnect.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_tcdm_interconnect.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/isolde_log_interconnect.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/hwe/isolde_redmule_top.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/rtl/noc/isolde_router.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/tb/tb_tcdm_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/tb/monitor/perfCounters.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/tb/monitor/isolde_hci_monitor.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/tb/tb_sram_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/vendor/isolde-soc/tb/tb_axi_mem.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/rtl/soc/aida_lca_package.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/rtl/soc/aida_lca.sv
/home/samuel_matea/ws-isolde/ibex_sam/isolde/lca_system/tb/tb_spm.sv

