/*=======================================================================================*/
/*  This Sail RISC-V architecture model, comprising all files and                        */
/*  directories except where otherwise noted is subject the BSD                          */
/*  two-clause license in the LICENSE file.                                              */
/*                                                                                       */
/*  SPDX-License-Identifier: BSD-2-Clause                                                */
/*=======================================================================================*/

termination_measure walk39(_,_,_,_,_,_,level,_, _) = level
termination_measure walk48(_,_,_,_,_,_,level,_, _) = level
