# Define the RTL + Spike cosimulation target for one test iteration.
#
# This file encapsulates the run step after all inputs are prepared:
#   - launch the RTL simulator on the generated binary,
#   - run the log analysis step.
#
# Snippy.cmake prepares the inputs, while this file owns the simulation target.
#
# The simulator-specific command line is delegated to the Ibex DV Makefile
# through GOAL=snippy_rtl_sim_run. CMake passes only Snippy payload paths;
# Ibex's rtl_simulation.yaml decides how the selected simulator is invoked.
#
# Runtime artifacts are owned by the Ibex flow. run_snippy_rtl.py exports each
# Snippy run directly into the standard Ibex run/tests/<testdotseed> layout.

function(ibex_add_cosimulation_target)
    set(options)
    set(oneValueArgs
        TARGET_NAME
        YAML_NAME
        ITER
        ITER_DIR
        LINKED_ELF
        ELF_LAYOUT
        SNIPPY_LOG
    )
    cmake_parse_arguments(COSIM "${options}" "${oneValueArgs}" "" ${ARGN})

    if(NOT COSIM_TARGET_NAME)
        message(FATAL_ERROR "ibex_add_cosimulation_target: TARGET_NAME is required")
    endif()

    if(NOT COSIM_YAML_NAME)
        message(FATAL_ERROR "ibex_add_cosimulation_target: YAML_NAME is required")
    endif()

    if(NOT DEFINED COSIM_ITER)
        message(FATAL_ERROR "ibex_add_cosimulation_target: ITER is required")
    endif()

    if(NOT COSIM_ITER_DIR)
        message(FATAL_ERROR "ibex_add_cosimulation_target: ITER_DIR is required")
    endif()

    if(NOT COSIM_LINKED_ELF)
        message(FATAL_ERROR "ibex_add_cosimulation_target: LINKED_ELF is required")
    endif()

    if(NOT COSIM_ELF_LAYOUT)
        message(FATAL_ERROR "ibex_add_cosimulation_target: ELF_LAYOUT is required")
    endif()

    if(NOT COSIM_SNIPPY_LOG)
        message(FATAL_ERROR "ibex_add_cosimulation_target: SNIPPY_LOG is required")
    endif()

    find_program(PYTHON3_EXECUTABLE NAMES python3 python REQUIRED)

    set(ITER_RESULT_JSON "${COSIM_ITER_DIR}/result.json")

    # Aggregate structured summary:
    #   build/summary/snippy_summary.json
    set(ANALYSIS_SUMMARY_JSON "${DIR_SUMMARY}/snippy_summary.json")

    set(COMMON_RUN_DEPS
        ${COSIM_LINKED_ELF}
        ${COSIM_ELF_LAYOUT}
        ${COSIM_SNIPPY_LOG}
        rtl_tb_compile
        build_riscv_dv
    )

    # This is the fallback seed passed to run_snippy_rtl.py / simulator command
    # line. It is not the real llvm-snippy instruction seed. The real Snippy
    # seed is auto-generated by llvm-snippy and later read from snippy.log by
    # run_snippy_rtl.py.
    if(RTL_FIXED_SEED)
        set(RUN_SEED_VALUE "${RTL_FIXED_SEED}")
    elseif(COV)
        set(RUN_SEED_VALUE "${SNIPPY_COV_SEED}")
    else()
        set(RUN_SEED_VALUE "${COSIM_ITER}")
    endif()

    ibex_make_env(IBEX_MAKE_ENV)
    ibex_make_common_args(IBEX_MAKE_COMMON_ARGS)

    set(SNIPPY_RTL_MAKE_ARGS
        run_existing_metadata
        GOAL=snippy_rtl_sim_run
        ${IBEX_MAKE_COMMON_ARGS}

        # Snippy/CMake run metadata.
        SNIPPY_TEST_NAME=${COSIM_YAML_NAME}
        SNIPPY_ITERATION=${COSIM_ITER}
        SNIPPY_RESULT_JSON=${ITER_RESULT_JSON}
        SNIPPY_SEED=${RUN_SEED_VALUE}
        SNIPPY_LINKED_ELF=${COSIM_LINKED_ELF}
        SNIPPY_ELF_LAYOUT=${COSIM_ELF_LAYOUT}
        SNIPPY_LOG=${COSIM_SNIPPY_LOG}

        # Custom ELF-layout UVM test settings consumed by ibex_sim.mk /
        # run_snippy_rtl.py. SIGNATURE_ADDR for upstream Ibex metadata is already
        # part of ${IBEX_MAKE_COMMON_ARGS}; keep this explicit variable for the
        # custom Python runner interface.
        SNIPPY_RTL_TEST=${SNIPPY_RTL_TEST}
        SNIPPY_TIMEOUT_S=${SNIPPY_TIMEOUT_S}
        SNIPPY_SIGNATURE_ADDR=${SIGNATURE_ADDR}
    )

    ibex_make_append_rv32zc_arg(SNIPPY_RTL_MAKE_ARGS)

    set(RUN_BYPRODUCTS
        ${ITER_RESULT_JSON}
    )

    if(COV)
        set(RUN_COMMENT "Running Snippy RTL simulation with coverage for ${COSIM_YAML_NAME}, iter ${COSIM_ITER}")
    else()
        set(RUN_COMMENT "Running Snippy RTL simulation for ${COSIM_YAML_NAME}, iter ${COSIM_ITER}")
    endif()

    add_custom_target(${COSIM_TARGET_NAME}
        COMMAND ${CMAKE_COMMAND} -E env
                ${IBEX_MAKE_ENV}
                ${IBEX_MAKE_PROGRAM}
                ${SNIPPY_RTL_MAKE_ARGS}

        COMMAND ${PYTHON3_EXECUTABLE}
                ${SNIPPY_LOG_ANALYZER}
                --result-json ${ITER_RESULT_JSON}
                --summary-json ${ANALYSIS_SUMMARY_JSON}

        DEPENDS ${COMMON_RUN_DEPS}
        BYPRODUCTS ${RUN_BYPRODUCTS}
        WORKING_DIRECTORY "${CORE_IBEX_ROOT}"
        COMMENT "${RUN_COMMENT}"
        VERBATIM
    )
endfunction()
